In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex=pickle.load(open(r'C:\Users\rajak\OneDrive\Documents\DATA\MACHINE_lEARNING\Feature_Engineering\Pipeline\ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open(r'C:\Users\rajak\OneDrive\Documents\DATA\MACHINE_lEARNING\Feature_Engineering\Pipeline\ohe_embarked.pkl','rb'))
clf=pickle.load(open(r'C:\Users\rajak\OneDrive\Documents\DATA\MACHINE_lEARNING\Feature_Engineering\Pipeline\clf.pkl','rb'))

In [11]:
##user input:Pclass	Sex	Age	SibSp	Parch	Fare	Embarked
test_input=np.array([3,'male',22,1,0,7.25,'S'],dtype='object').reshape(1,7)

In [12]:
test_input

array([[3, 'male', 22, 1, 0, 7.25, 'S']], dtype=object)

In [20]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\rajak\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [22]:
test_input_sex

array([[0., 1.]])

In [24]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [25]:
test_input_embarked

array([[0., 0., 1.]])

In [26]:
test_input_age=test_input[:,2].reshape(1,1)

In [30]:
test_input_age


array([[22]], dtype=object)

In [29]:
test_input[:,[0,3,4,5]]

array([[3, 1, 0, 7.25]], dtype=object)

In [37]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [38]:
test_input_transformed.shape

(1, 10)

In [39]:
clf.predict(test_input_transformed)

array([0], dtype=int64)

In [40]:
#Here maintaing the production code is very much much difficult.Different steps has to perform in speciofic order 
#Error in any steps may lead to the wrong prediction