In [44]:
import numpy as np
import pandas as pd


In [45]:
np.random.seed(23)
mu_v1=np.array([0,0,0])
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [46]:
class1_sample=np.random.multivariate_normal(mu_v1,cov_mat1,20)
df=pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

In [47]:
df

feature1  feature2  feature3  target
0   0.666988  0.025813 -0.777619       1
1   0.948634  0.701672 -1.051082       1
2  -0.367548 -1.137460 -1.322148       1
3   1.772258 -0.347459  0.670140       1
4   0.322272  0.060343 -1.043450       1
5  -1.009942  0.441736  1.128877       1
6  -1.838068 -0.938769 -0.201841       1
7   1.045371  0.538162  0.812119       1
8   0.241106 -0.952510 -0.136267       1
9   1.267248  0.173634 -1.223255       1
10  1.415320  0.457711  0.728876       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
14  0.420623  0.411620 -0.071324       1
15 -0.045438  1.040886 -0.094035       1
16 -0.420844 -0.551989 -0.121098       1
17  0.190141  0.512137  0.131538       1
18 -0.331617 -1.632386  0.619114       1
19 -0.992574 -0.161346  1.192404       1

In [48]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)
df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0
df = df.append(df1,ignore_index=True)
df

C:\Users\rajak\AppData\Local\Temp\ipykernel_21120\1975085243.py:7: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.



feature1  feature2  feature3  target
0   0.666988  0.025813 -0.777619       1
1   0.948634  0.701672 -1.051082       1
2  -0.367548 -1.137460 -1.322148       1
3   1.772258 -0.347459  0.670140       1
4   0.322272  0.060343 -1.043450       1
5  -1.009942  0.441736  1.128877       1
6  -1.838068 -0.938769 -0.201841       1
7   1.045371  0.538162  0.812119       1
8   0.241106 -0.952510 -0.136267       1
9   1.267248  0.173634 -1.223255       1
10  1.415320  0.457711  0.728876       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
14  0.420623  0.411620 -0.071324       1
15 -0.045438  1.040886 -0.094035       1
16 -0.420844 -0.551989 -0.121098       1
17  0.190141  0.512137  0.131538       1
18 -0.331617 -1.632386  0.619114       1
19 -0.992574 -0.161346  1.192404       1
20  1.250737  0.186384  1.703624       0
21  0.731858  0.517441  2.244610       0
22  1.676860  4.187503 -0.080565       0
23  1.010229  1.437830  2.327788       0
24  0.748855  2.593111  1.170818       0
25  0.290746  0.866975  0.982643       0
26  0.898907  0.435960  0.820964       0
27  2.011059  1.920996  2.933090       0
28  0.204637 -0.011535  3.150780       0
29  1.425140  1.441152  0.182561       0
30  1.437892  1.099723  1.065406       0
31  2.224431  0.230401  1.192120       0
32 -0.723253  1.461259 -0.085367       0
33  2.823378 -0.332863  2.637391       0
34  0.177061 -0.598109  1.226512       0
35  1.233898  0.052778 -0.261576       0
36 -1.389866  0.666726  1.343517       0
37 -1.027861  1.131416  2.603234       0
38 -0.764314  1.566504  1.548788       0
39  0.384865  1.323546 -0.103193       0

In [49]:
df=df.sample(40)

In [50]:
df

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
29  1.425140  1.441152  0.182561       0
31  2.224431  0.230401  1.192120       0
4   0.322272  0.060343 -1.043450       1
32 -0.723253  1.461259 -0.085367       0
33  2.823378 -0.332863  2.637391       0
36 -1.389866  0.666726  1.343517       0
18 -0.331617 -1.632386  0.619114       1
0   0.666988  0.025813 -0.777619       1
5  -1.009942  0.441736  1.128877       1
39  0.384865  1.323546 -0.103193       0
22  1.676860  4.187503 -0.080565       0
8   0.241106 -0.952510 -0.136267       1
15 -0.045438  1.040886 -0.094035       1
19 -0.992574 -0.161346  1.192404       1
30  1.437892  1.099723  1.065406       0
25  0.290746  0.866975  0.982643       0
21  0.731858  0.517441  2.244610       0
37 -1.027861  1.131416  2.603234       0
16 -0.420844 -0.551989 -0.121098       1
38 -0.764314  1.566504  1.548788       0
27  2.011059  1.920996  2.933090       0
26  0.898907  0.435960  0.820964       0
23  1.010229  1.437830  2.327788       0
1   0.948634  0.701672 -1.051082       1
10  1.415320  0.457711  0.728876       1
20  1.250737  0.186384  1.703624       0
28  0.204637 -0.011535  3.150780       0
24  0.748855  2.593111  1.170818       0
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
17  0.190141  0.512137  0.131538       1
13 -0.022539  0.013422  0.935945       1
9   1.267248  0.173634 -1.223255       1
35  1.233898  0.052778 -0.261576       0
3   1.772258 -0.347459  0.670140       1

In [40]:
import plotly.express as px
fig=px.scatter_3d(df,x=df['feature1'],y=df['feature2'],z=df['feature3'],color=df['target'].astype(str))
# fig.update_traces(marker=dict(size=12,
#                               line=dict(width=2,
#                                         color='DarkSlateGrey')),
#                   selector=dict(mode='markers'))
fig.show()

In [51]:
df.iloc[:,0:3]

feature1  feature2  feature3
2  -0.367548 -1.137460 -1.322148
34  0.177061 -0.598109  1.226512
14  0.420623  0.411620 -0.071324
11  1.968435 -0.547788 -0.679418
12 -2.506230  0.146960  0.606195
29  1.425140  1.441152  0.182561
31  2.224431  0.230401  1.192120
4   0.322272  0.060343 -1.043450
32 -0.723253  1.461259 -0.085367
33  2.823378 -0.332863  2.637391
36 -1.389866  0.666726  1.343517
18 -0.331617 -1.632386  0.619114
0   0.666988  0.025813 -0.777619
5  -1.009942  0.441736  1.128877
39  0.384865  1.323546 -0.103193
22  1.676860  4.187503 -0.080565
8   0.241106 -0.952510 -0.136267
15 -0.045438  1.040886 -0.094035
19 -0.992574 -0.161346  1.192404
30  1.437892  1.099723  1.065406
25  0.290746  0.866975  0.982643
21  0.731858  0.517441  2.244610
37 -1.027861  1.131416  2.603234
16 -0.420844 -0.551989 -0.121098
38 -0.764314  1.566504  1.548788
27  2.011059  1.920996  2.933090
26  0.898907  0.435960  0.820964
23  1.010229  1.437830  2.327788
1   0.948634  0.701672 -1.051082
10  1.415320  0.457711  0.728876
20  1.250737  0.186384  1.703624
28  0.204637 -0.011535  3.150780
24  0.748855  2.593111  1.170818
7   1.045371  0.538162  0.812119
6  -1.838068 -0.938769 -0.201841
17  0.190141  0.512137  0.131538
13 -0.022539  0.013422  0.935945
9   1.267248  0.173634 -1.223255
35  1.233898  0.052778 -0.261576
3   1.772258 -0.347459  0.670140

In [52]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df.iloc[:,0:3]=scaler.fit_transform(df.iloc[:,0:3])

In [53]:
df.iloc[:,0:3]

feature1  feature2  feature3
2  -0.700809 -1.525586 -1.749156
34 -0.224481 -1.010757  0.491251
14 -0.011456 -0.046935 -0.649616
11  1.342296 -0.962723 -1.184163
12 -2.571350 -0.299561 -0.054040
29  0.867118  0.935791 -0.426437
31  1.566196 -0.219914  0.461019
4  -0.097477 -0.382241 -1.504166
32 -1.011917  0.954984 -0.661960
33  2.090049 -0.757570  1.731490
36 -1.594952  0.196574  0.594105
18 -0.669383 -1.998011 -0.042684
0   0.204020 -0.415201 -1.270487
5  -1.262661 -0.018187  0.405425
39 -0.042731  0.823531 -0.677631
22  1.087278  3.557281 -0.657739
8  -0.168466 -1.349045 -0.706704
15 -0.419084  0.553723 -0.669580
19 -1.247471 -0.593851  0.461269
30  0.878271  0.609885  0.349631
25 -0.125050  0.387719  0.276878
21  0.260757  0.054075  1.386215
37 -1.278334  0.640137  1.701464
16 -0.747423 -0.966733 -0.693369
38 -1.047829  1.055444  0.774549
27  1.379576  1.393819  1.991425
26  0.406862 -0.023700  0.134754
23  0.504227  0.932620  1.459332
1   0.450354  0.229931 -1.510875
10  0.858529 -0.002939  0.053803
20  0.714580 -0.261930  0.910658
28 -0.200363 -0.450851  2.182786
24  0.275623  2.035377  0.442293
7   0.534963  0.073855  0.126978
6  -1.986959 -1.335928 -0.764347
17 -0.213041  0.049013 -0.471289
13 -0.399056 -0.427028  0.235828
9   0.729022 -0.274101 -1.662224
35  0.699853 -0.389462 -0.816857
3   1.170715 -0.771502  0.002171

In [54]:
X=df.drop('target',axis=1)

In [55]:
df.iloc[:,0:3]=scaler.fit_transform(X)

In [56]:
df.iloc[:,0:3]

feature1  feature2  feature3
2  -0.700809 -1.525586 -1.749156
34 -0.224481 -1.010757  0.491251
14 -0.011456 -0.046935 -0.649616
11  1.342296 -0.962723 -1.184163
12 -2.571350 -0.299561 -0.054040
29  0.867118  0.935791 -0.426437
31  1.566196 -0.219914  0.461019
4  -0.097477 -0.382241 -1.504166
32 -1.011917  0.954984 -0.661960
33  2.090049 -0.757570  1.731490
36 -1.594952  0.196574  0.594105
18 -0.669383 -1.998011 -0.042684
0   0.204020 -0.415201 -1.270487
5  -1.262661 -0.018187  0.405425
39 -0.042731  0.823531 -0.677631
22  1.087278  3.557281 -0.657739
8  -0.168466 -1.349045 -0.706704
15 -0.419084  0.553723 -0.669580
19 -1.247471 -0.593851  0.461269
30  0.878271  0.609885  0.349631
25 -0.125050  0.387719  0.276878
21  0.260757  0.054075  1.386215
37 -1.278334  0.640137  1.701464
16 -0.747423 -0.966733 -0.693369
38 -1.047829  1.055444  0.774549
27  1.379576  1.393819  1.991425
26  0.406862 -0.023700  0.134754
23  0.504227  0.932620  1.459332
1   0.450354  0.229931 -1.510875
10  0.858529 -0.002939  0.053803
20  0.714580 -0.261930  0.910658
28 -0.200363 -0.450851  2.182786
24  0.275623  2.035377  0.442293
7   0.534963  0.073855  0.126978
6  -1.986959 -1.335928 -0.764347
17 -0.213041  0.049013 -0.471289
13 -0.399056 -0.427028  0.235828
9   0.729022 -0.274101 -1.662224
35  0.699853 -0.389462 -0.816857
3   1.170715 -0.771502  0.002171

In [61]:
covariance_matrix=np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])

In [62]:
covariance_matrix

array([[1.02564103, 0.20478114, 0.080118  ],
       [0.20478114, 1.02564103, 0.19838882],
       [0.080118  , 0.19838882, 1.02564103]])

In [63]:
eigen_values,eigen_vectors=np.linalg.eig(covariance_matrix)

In [64]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [65]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [77]:
pc=eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [78]:
transformed_df=np.dot(df.iloc[:,0:3],pc.T)

In [81]:
new_df=pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target']=df['target'].values

In [82]:
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [88]:
fig=px.scatter(new_df,x='PC1',y='PC2',color=new_df['target'].astype(str))
fig.show()              
               